### ISSUE TITLE
Refresh/Update Blueprint Actor in all views

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#518]
I re-assigned materials to static mesh components within a blueprint actor.
The assignment itself works fine, but the materials don't udpate/refresh withn the bp-editor viewport and also not in other views, where the actor is referenced - e.g. the level viewport.

Is there any way to refresh/udpate an actor in all views?

Thanks!

**Comment by rdeioris** [comment]
Hi Lars, do you call post_edit_change() after having reassigned the material ?

**Comment by LarsGroh** [comment]
Tried that - doesn't show any effect.

**Comment by rdeioris** [comment]
It looks like 4.20 changed he way editors are notified of property changes. I will try to fix it asap

**Comment by rdeioris** [comment]
check latest code, i have implemented 'archetypes' propagation: (explained at the end of this section: https://github.com/20tab/UnrealEnginePython/blob/master/README.md#native-methods-vs-reflection).

Let me know how it works for you

**Comment by Schizo** [comment]
I still see this issue for example when I'm adding instances to an `HISM`

```
import unreal_engine as ue
from unreal_engine.classes import InstancedStaticMeshComponent
from unreal_engine.structs import InstancedStaticMeshInstanceData, Matrix, Plane
from unreal_engine import FTransform, FVector, FRotator, FQuat
import pickle




actor = ue.editor_get_selected_actors()[0]
instanced_component = actor.get_component_by_type(InstancedStaticMeshComponent)
mesh = ue.get_selected_assets()[0]
instanced_component.StaticMesh = mesh
o = 100

with open ('D:/arrows.pickle', 'rb') as fp:
    data = pickle.load(fp)

instanced_component = actor.get_component_by_type(InstancedStaticMeshComponent)
instanced_component.PerInstanceSMData = [InstancedStaticMeshInstanceData(Transform=FTransform(FVector(i[2]*o, i[1]*o, i[0]*o), FQuat(i[3], i[4], i[5], i[6])).get_matrix()) for i in data]
actor.post_edit_change()
instanced_component.post_edit_change()
```

post_edit_change() doesn't seem to have an effect, although it rarely sometimes works, still don't know what causes it to stop.
